### ISSUE TITLE
Graph doesn't display properly for the Cooling Fan predefined sensor

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#97]
First, thanks for all the great progress in stamping out bugs!!!
Second, I noticed that the graph defined by the fan sensor predefined value is not right:

1. The graph show a ramp up while the true graph is zig-zaggy (as confirmed by the mini-graph overlay and by the actual gcode)
2. The X-axis graph time is <60min even though it is set for 3600 seconds and has been printing for 90 minutes

Note that despite the wrong graph, the min=0 and max=30 values are probably right (though not sure about the average)

![image](https://user-images.githubusercontent.com/1993858/212724681-853bfd04-5f08-447f-9d93-ef9544bab079.png)

Note that my configs for the sensor are as follows:
```
cu1:
        cmd: ^M106.*?S([^ ]+)
        colorChangeLevel: '1'
        colorIcons: true
        decSep: ','
        gHisSecs: '3600'
        gMax: ''
        gMin: ''
        graphSettings:
          color: '#af0096'
          forceStyle: true
          height: 50
          opa: '.5'
          show: true
          width: 1
        hideIfNoPrinter: false
        hideOnNoTarget: false
        icon: fas fa-fan
        interval: 25
        isTemp: false
        label: 'Fan '
        name: Cooling fan speed
        noDigits: 0
        postCalc: X/255*100
        show: true
        showPopover: true
        showSep: false
        showUnit: false
        type: gcOut
        unit: '%'
        updated: 1673843347689
        waitForPrint: true
        width: 0
```

Note that all my other sensors seem to be working fine whether built-ins whether custom shell commands or whether based on custom gcode regex.

Sorry for all the issues but hopefully this will help make your AWESOME plugin even better! Thanks!
